postgres:
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - "postgresql:/var/lib/postgresql"
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=db_name
